### ISSUE TITLE
Having already drawn content appears when another person joins

### ISSUE THREAD

**Issue by moeenio** [Advaith3600/Whiteboard#1]
If we draw something, then somebody else joins, he will not see what has already been drawn, even though his changes will be reflected. Same if we refresh the page.

**Comment by Advaith3600** [comment]
Thanks for the information. I will fix that issue on my next commit. 😄

**Comment by Advaith3600** [comment]
Hey, I know it has been a long time, but I have updated the project with this feature. Please have a look if you are still interested. 

The app also supports rooms, you are automatically added to a room when you first enter, and the room link can be shared with others to sync the drawing. A new room can be created by going to `/`.

**Comment by moeenio** [comment]
Huh, I do not remember this. Neat.
